# Generated by Django 5.1.1 on 2024-10-08 11:30

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام دسته بندی')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='shop_catego_name_289c7e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='shop/product_images/%Y/%m/', verbose_name='تصویر')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('real_price', models.PositiveIntegerField(verbose_name='قیمت اصلی')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت بعد از تخفیف')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='دسته بندی')),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-created'], name='shop_produc_created_ef211c_idx'), models.Index(fields=['name'], name='shop_produc_name_a2070e_idx')],
            },
        ),
    ]
