# Generated by Django 5.1.1 on 2024-10-08 11:30

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(default='', max_length=100, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('register_date', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ پیوستن')),
                ('last_visit_date', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین مراجه')),
                ('visit_count', models.PositiveIntegerField(default=0, verbose_name='تعداد مراجعه')),
                ('kind', models.CharField(choices=[('NORMAL', 'مشتری معمولی'), ('KNOWN', 'مشتری آشنا'), ('LOYAL', 'مشتری وفادار')], default='NORMAL', max_length=6, verbose_name='نوع')),
            ],
            options={
                'ordering': ['-register_date'],
                'indexes': [models.Index(fields=['phone', '-register_date'], name='club_custom_phone_30ddde_idx')],
            },
        ),
    ]
